# -*- coding: utf-8 -*-
"""4 March_Assig(Plotly).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L6RyXzUvnp0Qi6FEPgbSodzweWptuegp

Q1. Load the "titanic" dataset using the load_dataset function of seaborn. Use Plotly express to plot a
scatter plot for age and fare columns in the titanic dataset.

Answer:-To load the "titanic" dataset from seaborn and create a scatter plot for the "age" and "fare" columns using Plotly express, you can use the following code:
"""

import seaborn as sns
import plotly.express as px

# Load the titanic dataset
titanic_df = sns.load_dataset('titanic')

# Create a scatter plot with age and fare
fig = px.scatter(titanic_df, x='age', y='fare')

# Show the plot
fig.show()

"""This will create a scatter plot showing the relationship between the "age" and "fare" columns in the "titanic" dataset. Each dot represents a passenger, with the x-axis showing their age and the y-axis showing the fare they paid.

Q2. Using the tips dataset in the Plotly library, plot a box plot using Plotly express.

Answer:-To plot a box plot for the "tips" dataset using Plotly express, you can use the following code:
"""

import plotly.express as px
tips_df = px.data.tips()

# Create a box plot for total_bill column
fig = px.box(tips_df, y='total_bill')

# Show the plot
fig.show()

"""This will create a box plot for the "total_bill" column in the "tips" dataset. The y-axis shows the values of the "total_bill" column and the box plot shows the distribution of these values. The box represents the interquartile range (IQR) of the data, with the middle line representing the median. The whiskers extend to the minimum and maximum values within 1.5 times the IQR, and any points outside this range are shown as outliers.

Q3. Using the tips dataset in the Plotly library, Plot a histogram for x= "sex" and y="total_bill" column in
the tips dataset. Also, use the "smoker" column with the pattern_shape parameter and the "day"
column with the color parameter.

To plot a histogram for the "sex" and "total_bill" columns in the "tips" dataset using Plotly express, with the "smoker" column using the pattern_shape parameter and the "day" column using the color parameter, you can use the following code:
"""

import plotly.express as px
tips_df = px.data.tips()

# Create a histogram for sex and total_bill, with smoker using pattern_shape and day using color
fig = px.histogram(tips_df, x='sex', y='total_bill', color='day', pattern_shape='smoker')

# Show the plot
fig.show()

"""This will create a histogram for the "sex" and "total_bill" columns in the "tips" dataset, with the "smoker" column represented by different patterns and the "day" column represented by different colors. The x-axis shows the "sex" categories and the y-axis shows the "total_bill" values. Each bar represents the frequency of "total_bill" values for each "sex" category. The patterns in each bar represent the "smoker" categories and the colors represent the "day" categories.

Q4. Using the iris dataset in the Plotly library, Plot a scatter matrix plot, using the "species" column for
the color parameter.
Note: Use "sepal_length", "sepal_width", "petal_length", "petal_width" columns only with the
dimensions parameter.

Answer:-To plot a scatter matrix plot for the "iris" dataset using Plotly express, with the "species" column used for the color parameter and only using the "sepal_length", "sepal_width", "petal_length", and "petal_width" columns with the dimensions parameter, you can use the following code:
"""

import plotly.express as px
iris_df = px.data.iris()

# Create a scatter matrix plot with species as the color parameter and dimensions for the four columns
fig = px.scatter_matrix(iris_df, dimensions=["sepal_length", "sepal_width", "petal_length", "petal_width"], color="species")

# Show the plot
fig.show()

"""This will create a scatter matrix plot for the "iris" dataset, with the x- and y-axes representing the four columns ("sepal_length", "sepal_width", "petal_length", and "petal_width") and each dot representing a data point. The plots on the diagonal show the distribution of each variable, while the other plots show the relationship between each pair of variables. The "species" column is used for the color parameter to distinguish between the three species of iris.

Q5. What is Distplot? Using Plotly express, plot a distplot.

Distplot is a visualization tool used to represent the distribution of a dataset. It is a combination of a histogram and a kernel density plot, and it can be used to visualize the shape of the data distribution and to identify the presence of outliers or skewness.

Here is an example of how to create a distplot using Plotly express in Python:
"""

import plotly.express as px
import seaborn as sns
tips = sns.load_dataset("tips")
fig = px.histogram(tips, x="total_bill", nbins=30, opacity=0.7, color_discrete_sequence=['indianred'])
fig.show()

"""This code loads the tips dataset from the seaborn library, which contains information about the total bill and tip amount for customers at a restaurant. Then, it creates a distplot of the total_bill column using Plotly express. The nbins argument specifies the number of bins in the histogram, and the opacity argument controls the transparency of the bars. The color_discrete_sequence argument sets the color of the bars to "indianred".

The resulting plot will show the distribution of the total_bill column, with the x-axis showing the values and the y-axis showing the frequency or density of those values.

Thanks
"""